=== BoostV/process-optimizer-frontend/packages/core/src/common/util/migration/schemas/21.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "lastEvaluationHash": {
      "type": "string"
    },
    "changedSinceLastEvaluation": {
      "type": "boolean"
    },
    "info": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "swVersion": {
          "type": "string"
        },
        "dataFormatVersion": {
          "type": "string",
          "const": "21"
        },
        "version": {
          "type": "number"
        },
        "lastModified": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "extras": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        }
      },
      "required": [
        "name",
        "description",
        "swVersion",
        "dataFormatVersion",
        "version",
        "lastModified",
        "createdAt",
        "extras"
      ],
      "additionalProperties": false
    },
    "extras": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {}
    },
    "categoricalVariables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "enabled": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "description",
          "options",
          "enabled"
        ],
        "additionalProperties": false
      }
    },
    "valueVariables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "anyOf": [
              {
                "type": "string",
                "const": "discrete"
              },
              {
                "type": "string",
                "const": "continuous"
              }
            ]
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "min": {
            "type": "number"
          },
          "max": {
            "type": "number"
          },
          "enabled": {
            "type": "boolean"
          }
        },
        "required": [
          "type",
          "name",
          "description",
          "min",
          "max",
          "enabled"
        ],
        "additionalProperties": false
      }
    },
    "scoreVariables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string",
                "const": "quality"
              },
              {
                "type": "string",
                "const": "cost"
              }
            ]
          },
          "label": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "enabled": {
            "type": "boolean"
          },
          "scoreFunction": {
            "type": "object",
            "properties": {
              "expression": {
                "type": "string"
              },
              "variables": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "symbol": {
                      "type": "string"
                    },
                    "source": {
                      "type": "string",
                      "enum": [
                        "response",
                        "factor"
                      ]
                    },
                    "factorName": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "symbol",
                    "source"
                  ],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "expression",
              "variables"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "name",
          "label",
          "description",
          "enabled"
        ],
        "additionalProperties": false
      }
    },
    "constraints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "const": "sum"
          },
          "value": {
            "type": "number"
          },
          "dimensions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "type",
          "value",
          "dimensions"
        ],
        "additionalProperties": false
      }
    },
    "optimizerConfig": {
      "type": "object",
      "properties": {
        "baseEstimator": {
          "type": "string"
        },
        "acqFunc": {
          "type": "string"
        },
        "initialPoints": {
          "type": "number"
        },
        "kappa": {
          "type": "number"
        },
        "xi": {
          "type": "number"
        }
      },
      "required": [
        "baseEstimator",
        "acqFunc",
        "initialPoints",
        "kappa",
        "xi"
      ],
      "additionalProperties": false
    },
    "results": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "plots": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "plot": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "plot"
            ],
            "additionalProperties": false
          }
        },
        "next": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "number"
                },
                {
                  "type": "string"
                }
              ]
            }
          }
        },
        "pickled": {
          "type": "string"
        },
        "expectedMinimum": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              {
                "type": "number"
              }
            ]
          }
        },
        "extras": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        }
      },
      "required": [
        "id",
        "plots",
        "next",
        "pickled",
        "expectedMinimum",
        "extras"
      ],
      "additionalProperties": false
    },
    "dataPoints": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "meta": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "enabled": {
                "type": "boolean"
              },
              "valid": {
                "type": "boolean"
              },
              "description": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "enabled",
              "valid"
            ],
            "additionalProperties": false
          },
          "data": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "const": "numeric"
                    },
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "type",
                    "name",
                    "value"
                  ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "const": "categorical"
                    },
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "type",
                    "name",
                    "value"
                  ],
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string",
                      "const": "score"
                    },
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "type",
                    "name",
                    "value"
                  ],
                  "additionalProperties": false
                }
              ]
            }
          },
          "responses": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "scoreName": {
                  "anyOf": [
                    {
                      "type": "string",
                      "const": "quality"
                    },
                    {
                      "type": "string",
                      "const": "cost"
                    }
                  ]
                },
                "useFunction": {
                  "type": "boolean"
                },
                "values": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "symbol": {
                        "type": "string"
                      },
                      "value": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "symbol",
                      "value"
                    ],
                    "additionalProperties": false
                  }
                }
              },
              "required": [
                "scoreName",
                "useFunction",
                "values"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "meta",
          "data"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "changedSinceLastEvaluation",
    "info",
    "extras",
    "categoricalVariables",
    "valueVariables",
    "scoreVariables",
    "constraints",
    "optimizerConfig",
    "results",
    "dataPoints"
  ],
  "additionalProperties": false
}

=== BoostV/process-optimizer-frontend/packages/core/src/common/util/migration/data-formats/21.json
{
  "id": "1234",
  "changedSinceLastEvaluation": true,
  "lastEvaluationHash": "never-calculated",
  "info": {
    "dataFormatVersion": "21",
    "swVersion": "v1.2.0-16",
    "name": "Cake",
    "description": "Yummy",
    "version": 0,
    "extras": {},
    "lastModified": "",
    "createdAt": ""
  },
  "categoricalVariables": [
    {
      "name": "Icing",
      "description": "Sugary",
      "options": ["White", "Brown"],
      "enabled": true
    }
  ],
  "valueVariables": [
    {
      "name": "name1",
      "description": "desc1",
      "min": 10,
      "max": 100,
      "type": "discrete",
      "enabled": true
    },
    {
      "name": "name2",
      "description": "desc2",
      "min": 10.2,
      "max": 100.3,
      "type": "continuous",
      "enabled": true
    }
  ],
  "scoreVariables": [
    {
      "name": "quality",
      "label": "Quality (0-5)",
      "description": "",
      "enabled": true
    }
  ],
  "constraints": [
    {
      "type": "sum",
      "dimensions": [],
      "value": 0
    }
  ],
  "optimizerConfig": {
    "baseEstimator": "GP",
    "acqFunc": "EI",
    "initialPoints": 3,
    "kappa": 1.96,
    "xi": 0.01
  },
  "results": {
    "id": "",
    "next": [[]],
    "plots": [],
    "pickled": "",
    "expectedMinimum": [],
    "extras": {}
  },
  "dataPoints": [
    {
      "meta": {
        "enabled": true,
        "valid": true,
        "id": 1
      },
      "data": [
        {
          "type": "categorical",
          "name": "Icing",
          "value": "Brown"
        },
        {
          "type": "numeric",
          "name": "name1",
          "value": 10
        },
        {
          "type": "numeric",
          "name": "name2",
          "value": 10.2
        },
        {
          "type": "score",
          "name": "quality",
          "value": 0.5
        }
      ]
    }
  ],
  "extras": {
    "experimentSuggestionCount": 1
  }
}
